# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cong Pham
email: me@cong.ph
phone: +84 91 803 2499
description: > # this means to ignore newlines until "baseurl:"
  Cong Pham's humble profile site. Check out my links underneath or contact me via email.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cong.ph" # the base hostname & protocol for your site
twitter_username: congphammm
github_username:  congp
dribbble_username: cong
instagram_username: cong.ph

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
